-- ============================================================
-- Database schema expected by the app (Supabase / Postgres)
-- ============================================================
-- English schema: "categories" and "items", replacing the old
-- Portuguese "categorias" / "itens" tables. Column names and
-- seed data below are translated from the original data.
-- ============================================================

-- ------------------------------------------------------------
-- Table: categories
-- ------------------------------------------------------------
create table if not exists categories (
  id   bigint generated by default as identity primary key,
  name text   not null unique
);

-- ------------------------------------------------------------
-- Table: items
-- "category" is a foreign key into categories(name).
-- ------------------------------------------------------------
create table if not exists items (
  id             bigint generated by default as identity primary key,
  name           text    not null,
  category       text    not null references categories (name) on update cascade,
  quantity       int4    not null default 0,
  photo_url      text,
  price          numeric(10, 2) not null default 0,
  needs_purchase boolean not null default false,
  is_purchasing  boolean not null default false
);

-- ------------------------------------------------------------
-- Row Level Security: public read/write, matching the
-- "publishable" key used on the front end. Adjust as needed
-- if you add authentication later.
-- ------------------------------------------------------------
alter table categories enable row level security;
alter table items enable row level security;

create policy "Public read categories" on categories
  for select using (true);
create policy "Public insert categories" on categories
  for insert with check (true);

create policy "Public read items" on items
  for select using (true);
create policy "Public insert items" on items
  for insert with check (true);
create policy "Public update items" on items
  for update using (true) with check (true);
create policy "Public delete items" on items
  for delete using (true);

-- ------------------------------------------------------------
-- Seed data (translated from the original Portuguese rows)
-- ------------------------------------------------------------
insert into categories (id, name) values
  (1,  'Meat'),
  (2,  'Dairy'),
  (3,  'Sweets'),
  (4,  'Non-Perishables'),
  (6,  'Hygiene'),
  (7,  'Condiments'),
  (17, 'Vegetables'),
  (18, 'Fruits'),
  (19, 'Deli'),
  (20, 'Frozen'),
  (21, 'Beverages'),
  (22, 'Household Cleaning'),
  (23, 'Laundry Cleaning'),
  (24, 'Seasonings')
on conflict (id) do update set name = excluded.name;

select setval(pg_get_serial_sequence('categories', 'id'), (select max(id) from categories));

insert into items (id, name, category, quantity, photo_url, price, needs_purchase, is_purchasing) values
  (596, 'Fabric Softener',              'Laundry Cleaning',   0, null, 0,  false, false),
  (583, 'Bleach',                       'Household Cleaning', 0, null, 0,  false, false),
  (567, 'Sanitary Pads',                'Hygiene',             0, null, 23, false, false),
  (565, 'Pineapple',                    'Fruits',              0, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_rCxF-zyhwLLo8R2UvNzG92hc1fXX-mZ62axoYxnV7GfbAWtD3Prfl5mJlcyYNrKsRjDrSHUR-tbnCckGuvZfGSVlYDmX7DquP-cVGg&s=10', 0, false, false),
  (617, 'Granulated Sugar',             'Non-Perishables',     0, null, 0,  false, false),
  (549, 'Bacon Strips',                 'Meat',                0, null, 0,  false, false),
  (550, 'Ground Beef',                  'Meat',                0, null, 0,  false, false),
  (551, 'Sirloin Steak',                'Meat',                0, null, 0,  false, false),
  (552, 'Chicken Drumstick and Thigh',  'Meat',                0, null, 0,  false, false),
  (553, 'Frozen Tilapia Fillet',        'Meat',                0, null, 0,  false, false),
  (554, 'Calabrese Sausage',            'Meat',                0, null, 0,  false, false),
  (555, 'Chicken Breast',               'Meat',                0, null, 0,  false, false),
  (556, 'Ham',                          'Deli',                0, null, 0,  false, false),
  (557, 'Mozzarella Cheese',            'Deli',                0, null, 0,  false, false),
  (558, 'Orange',                       'Fruits',              0, null, 0,  false, false),
  (559, 'Lemon',                        'Fruits',              0, null, 0,  false, false),
  (560, 'Apple',                        'Fruits',              0, null, 0,  false, false),
  (561, 'Papaya',                       'Fruits',              0, null, 0,  false, false),
  (562, 'Watermelon',                   'Fruits',              0, null, 0,  false, false),
  (563, 'Melon',                        'Fruits',              0, null, 0,  false, false),
  (564, 'Grapes',                       'Fruits',              0, null, 0,  false, false),
  (566, 'Banana',                       'Fruits',              0, null, 0,  false, false),
  (568, 'Conditioner',                  'Hygiene',             0, null, 0,  false, false),
  (569, 'Aerosol Deodorant',            'Hygiene',             0, null, 0,  false, false),
  (570, 'Toothbrush',                   'Hygiene',             0, null, 0,  false, false),
  (571, 'Dental Floss',                 'Hygiene',             0, null, 0,  false, false),
  (572, 'Toilet Paper',                 'Hygiene',             0, null, 0,  false, false),
  (573, 'Toothpaste',                   'Hygiene',             0, null, 0,  false, false),
  (574, 'Bar Soap',                     'Hygiene',             0, null, 0,  false, false),
  (575, 'Shampoo',                      'Hygiene',             0, null, 0,  false, false),
  (576, 'Band-Aid',                     'Hygiene',             0, null, 0,  false, false),
  (577, 'Cotton Balls',                 'Hygiene',             0, null, 0,  false, false),
  (578, 'Sodium Percarbonate',          'Laundry Cleaning',    0, null, 0,  false, false),
  (579, 'Natural Yogurt',               'Dairy',               0, null, 0,  false, false),
  (580, 'Whole Milk',                   'Dairy',               0, null, 0,  false, false),
  (581, 'Butter',                       'Dairy',               0, null, 0,  false, false),
  (582, 'Milk',                         'Dairy',               0, null, 0,  false, false),
  (584, 'Baking Soda',                  'Household Cleaning',  0, null, 0,  false, false),
  (585, 'Kitchen Sponge',               'Household Cleaning',  0, null, 0,  false, false),
  (586, 'Multi-Purpose Wax Polish',     'Household Cleaning',  0, null, 0,  false, false),
  (587, 'Disinfectant',                 'Household Cleaning',  0, null, 0,  false, false),
  (588, 'Dish Soap',                    'Household Cleaning',  0, null, 0,  false, false),
  (589, 'Liquid Dish Soap',             'Household Cleaning',  0, null, 0,  false, false),
  (590, 'Steel Wool',                   'Household Cleaning',  0, null, 0,  false, false),
  (591, 'Glass Cleaner',                'Household Cleaning',  0, null, 0,  false, false),
  (592, 'Garbage Bags',                 'Household Cleaning',  0, null, 0,  false, false),
  (593, 'Powder Stain Remover',         'Household Cleaning',  0, null, 0,  false, false),
  (594, 'All-Purpose Cleaner (Veja)',   'Household Cleaning',  0, null, 0,  false, false),
  (595, 'Insect Spray',                 'Household Cleaning',  0, null, 0,  false, false),
  (597, 'Sodium Percarbonate',          'Laundry Cleaning',    0, null, 0,  false, false),
  (598, 'Powder Laundry Detergent',     'Laundry Cleaning',    0, null, 0,  false, false),
  (599, 'Powder Laundry Detergent',     'Laundry Cleaning',    0, null, 0,  false, false),
  (600, 'Spaghetti',                    'Non-Perishables',     0, null, 0,  false, false),
  (601, 'Tomato Sauce',                 'Non-Perishables',     0, null, 0,  false, false),
  (602, 'Soybean Oil',                  'Non-Perishables',     0, null, 0,  false, false),
  (603, 'Eggs',                         'Non-Perishables',     0, null, 0,  false, false),
  (604, 'French Bread',                 'Non-Perishables',     0, null, 0,  false, false),
  (605, 'Refined Salt',                 'Non-Perishables',     0, null, 0,  false, false),
  (606, 'Vinegar',                      'Non-Perishables',     0, null, 0,  false, false),
  (607, 'White Vinegar',                'Non-Perishables',     0, null, 0,  false, false),
  (608, 'Rice Vinegar',                 'Non-Perishables',     0, null, 0,  false, false),
  (609, 'Apple Cider Vinegar',          'Non-Perishables',     0, null, 0,  false, false),
  (610, 'Brown Rice',                   'Non-Perishables',     0, null, 0,  false, false),
  (611, 'White Rice',                   'Non-Perishables',     0, null, 0,  false, false),
  (612, 'Ground Coffee',                'Non-Perishables',     0, null, 0,  false, false),
  (613, 'Tomato Paste',                 'Non-Perishables',     0, null, 0,  false, false),
  (614, 'Wheat Flour',                  'Non-Perishables',     0, null, 0,  false, false),
  (615, 'Black Beans',                  'Non-Perishables',     0, null, 0,  false, false),
  (616, 'Carioca Beans',                'Non-Perishables',     0, null, 0,  false, false),
  (618, 'Basil',                        'Seasonings',          0, null, 0,  false, false),
  (619, 'Nutmeg',                       'Seasonings',          0, null, 0,  false, false),
  (620, 'Ready-Made Seasoning',         'Seasonings',          0, null, 0,  false, false),
  (621, 'Garlic',                       'Seasonings',          0, null, 0,  false, false),
  (622, 'Olive Oil',                    'Seasonings',          0, null, 0,  false, false),
  (623, 'Rosemary',                     'Seasonings',          0, null, 0,  false, false),
  (624, 'Chives',                       'Seasonings',          0, null, 0,  false, false),
  (625, 'Ground Cinnamon',              'Seasonings',          0, null, 0,  false, false),
  (626, 'Cilantro',                     'Seasonings',          0, null, 0,  false, false),
  (627, 'Annatto Seasoning (Colorau)',  'Seasonings',          0, null, 0,  false, false),
  (628, 'Ground Cumin',                 'Seasonings',          0, null, 0,  false, false),
  (629, 'Cloves',                       'Seasonings',          0, null, 0,  false, false),
  (630, 'Cloves',                       'Seasonings',          0, null, 0,  false, false),
  (631, 'Turmeric',                     'Seasonings',          0, null, 0,  false, false),
  (632, 'Ground Ginger',                'Seasonings',          0, null, 0,  false, false),
  (633, 'Mint',                         'Seasonings',          0, null, 0,  false, false),
  (634, 'Bay Leaf',                     'Seasonings',          0, null, 0,  false, false),
  (635, 'Oregano',                      'Seasonings',          0, null, 0,  false, false),
  (636, 'Smoked Paprika',               'Seasonings',          0, null, 0,  false, false),
  (637, 'Sweet Paprika',                'Seasonings',          0, null, 0,  false, false),
  (638, 'Hot Paprika',                  'Seasonings',          0, null, 0,  false, false),
  (639, 'White Peppercorn',             'Seasonings',          0, null, 0,  false, false),
  (640, 'White Peppercorn',             'Seasonings',          0, null, 0,  false, false),
  (641, 'Black Peppercorn',             'Seasonings',          0, null, 0,  false, false),
  (642, 'Parsley',                      'Seasonings',          0, null, 0,  false, false),
  (643, 'Sage',                         'Seasonings',          0, null, 0,  false, false),
  (644, 'Thyme',                        'Seasonings',          0, null, 0,  false, false),
  (645, 'Yellow Bell Pepper',           'Vegetables',          0, null, 0,  false, false),
  (646, 'Green Bell Pepper',            'Vegetables',          0, null, 0,  false, false),
  (647, 'Red Bell Pepper',              'Vegetables',          0, null, 0,  false, false),
  (648, 'Cabbage',                      'Vegetables',          0, null, 0,  false, false),
  (649, 'Arugula',                      'Vegetables',          0, null, 0,  false, false),
  (650, 'Green Beans',                  'Vegetables',          0, null, 0,  false, false),
  (652, 'Potato',                       'Vegetables',          0, null, 0,  false, false),
  (653, 'Onion',                        'Vegetables',          0, null, 0,  false, false),
  (654, 'Tomato',                       'Vegetables',          0, null, 0,  false, false),
  (656, 'Watercress',                   'Vegetables',          0, null, 0,  false, false),
  (657, 'Eggplant',                     'Vegetables',          0, null, 0,  false, false),
  (658, 'Broccoli',                     'Vegetables',          0, null, 0,  false, false),
  (659, 'Carrot',                       'Vegetables',          0, null, 0,  false, false),
  (660, 'Chayote',                      'Vegetables',          0, null, 0,  false, false),
  (661, 'Collard Greens',               'Vegetables',          0, null, 0,  false, false),
  (662, 'Spinach',                      'Vegetables',          0, null, 0,  false, false),
  (663, 'Chicken Nuggets',              'Frozen',              0, null, 0,  false, false),
  (665, 'Lasagna',                      'Frozen',              0, null, 0,  false, false),
  (666, 'Condensed Milk',               'Sweets',              0, null, 0,  false, false),
  (667, 'Heavy Cream',                  'Dairy',               0, null, 0,  false, false),
  (668, 'Baking Powder',                'Non-Perishables',     0, null, 0,  false, false),
  (669, 'Jam',                          'Non-Perishables',     0, null, 0,  false, false),
  (670, 'Ketchup',                      'Condiments',          0, null, 0,  false, false),
  (671, 'Mustard',                      'Condiments',          0, null, 0,  false, false),
  (672, 'Mayonnaise',                   'Condiments',          0, null, 0,  false, false),
  (673, 'Shoestring Potato Chips',      'Non-Perishables',     0, null, 0,  false, false),
  (674, 'Sliced Bread',                 'Non-Perishables',     0, null, 0,  false, false),
  (675, 'Cream Cheese Spread',          'Dairy',               0, null, 0,  false, false),
  (676, 'Apple Cookies',                'Non-Perishables',     0, null, 0,  false, false),
  (677, 'Coconut Cookies',              'Non-Perishables',     0, null, 0,  false, false),
  (678, 'Popcorn Kernels',              'Non-Perishables',     0, null, 0,  false, false),
  (680, 'Liquid Soap',                  'Hygiene',             0, null, 0,  false, false),
  (681, 'Wet Wipes',                    'Hygiene',             0, null, 0,  false, false),
  (682, 'Anti-Dandruff Shampoo',        'Hygiene',             0, null, 0,  false, false),
  (683, 'Gi''s Facial Soap',            'Hygiene',             0, null, 0,  false, false),
  (684, 'Ju''s Facial Soap',            'Hygiene',             0, null, 0,  false, false),
  (685, 'Stink Enemy Deodorant',        'Hygiene',             0, null, 0,  false, false),
  (686, 'Liquid Soap',                  'Hygiene',             0, null, 0,  false, false),
  (664, 'French Fries',                 'Frozen',              0, null, 25, false, false),
  (679, 'Cachaça (Brazilian Sugarcane Spirit)', 'Beverages',    0, null, 0,  false, false),
  (651, 'Lettuce',                      'Vegetables',          0, null, 0,  false, false)
on conflict (id) do update set
  name           = excluded.name,
  category       = excluded.category,
  photo_url      = excluded.photo_url,
  price          = excluded.price;

select setval(pg_get_serial_sequence('items', 'id'), (select max(id) from items));
